### ISSUE TITLE
installation fails in create_database.sql 

### ISSUE THREAD

**Issue by BramVan-Oosterhout** [Festivals-App/festivals-database#4]
Hi there,

I am installing the Festival App to have a look. The whole setup and layout of the code is really nice. All credit to you.

I am installing the Festival App from scratch. There is a problem in` festivals-database/database_scripts/create_database.sql` (line 82,83)

On installation the full table is created, including `event_is_scheduled` and `event_has_timeslot` (line 74,75)
Then line 82,83 creates those fields again, which fails.

I have worked around it by deleting line 82,83. But the script is set up to be re-runnable, so maybe this is not the right thing?

**Comment by Phisto** [comment]
hey bram,
i'm happy to hear that you have a look at my code, and that you like it so far :) The two lines you mentioned where from a time when i experimented with using alter table instructions to manage database creation/maintenance. I removed them.

I do think that the database management does have some automation needed, to be honest, in comparison to other parts of the infrastructure its hard to find good resources to take inspiration from on the internet, so if you have suggestions, feel free to share them with me :)

**Comment by BramVan-Oosterhout** [comment]
Hi,
Thanks for fixing this up. I appreciate it. 
For the moment I am still trying to get the app to install. If I can get that done, I may be able to help. 
let's see how things go.
